apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: postgresdatabase-sample-role-access
  namespace: demo
spec:
  roleRef:
    kind: PostgresRole
    name: postgresdatabase-sample-role
  subjects:
  - kind: ServiceAccount
    name: demo-pg
    namespace: demo