apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: postgres-secret-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
    namespace: demo
  postgres:
    databaseRef:
      name: demo-pg
      namespace: demo
    pluginName: "postgresql-database-plugin"