apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pg-custom-auth
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-custom-auth
              key: password
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config