apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schema-manager-role
rules:
- apiGroups:
  - "engine.kubevault.com"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"