apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-manager-test
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: rakibulhossain/schema-manager
        name: schema-manager-pod
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      serviceAccountName: schema-manager-controller-manager
